// <auto-generated />
using System;
using MentalCheck.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MentalCheck.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentalCheck.API.Models.Checkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CHECKIN");

                    b.Property<string>("LocalTrabalho")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("LOCAL_TRABALHO");

                    b.Property<int>("NivelCansaco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_CANSACO");

                    b.Property<int>("NivelEstresse")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_ESTRESSE");

                    b.Property<int>("NivelMotivacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_MOTIVACAO");

                    b.Property<int>("NivelSatisfacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_SATISFACAO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<int>("QualidadeSono")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUALIDADE_SONO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GS_CHECKIN", (string)null);
                });

            modelBuilder.Entity("MentalCheck.API.Models.Dica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("CondicaoAplicacao")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CONDICAO_APLICACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TITULO");

                    b.HasKey("Id");

                    b.ToTable("GS_DICA", (string)null);
                });

            modelBuilder.Entity("MentalCheck.API.Models.Insight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_INSIGHT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataIdentificacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_IDENTIFICACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GS_INSIGHT", (string)null);
                });

            modelBuilder.Entity("MentalCheck.API.Models.InsightDica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_INSIGHT_DICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRecomendacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RECOMENDACAO");

                    b.Property<int>("DicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DICA");

                    b.Property<int>("InsightId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_INSIGHT");

                    b.Property<string>("StatusVisualizacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_VISUALIZACAO");

                    b.HasKey("Id");

                    b.HasIndex("DicaId");

                    b.HasIndex("InsightId");

                    b.ToTable("GS_INSIGHT_DICA", (string)null);
                });

            modelBuilder.Entity("MentalCheck.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CARGO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("ModalidadeTrabalho")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("MODALIDADE_TRABALHO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("GS_USUARIO", (string)null);
                });

            modelBuilder.Entity("MentalCheck.API.Models.Checkin", b =>
                {
                    b.HasOne("MentalCheck.API.Models.Usuario", "Usuario")
                        .WithMany("Checkins")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MentalCheck.API.Models.Insight", b =>
                {
                    b.HasOne("MentalCheck.API.Models.Usuario", "Usuario")
                        .WithMany("Insights")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MentalCheck.API.Models.InsightDica", b =>
                {
                    b.HasOne("MentalCheck.API.Models.Dica", "Dica")
                        .WithMany("InsightDicas")
                        .HasForeignKey("DicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalCheck.API.Models.Insight", "Insight")
                        .WithMany("InsightDicas")
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dica");

                    b.Navigation("Insight");
                });

            modelBuilder.Entity("MentalCheck.API.Models.Dica", b =>
                {
                    b.Navigation("InsightDicas");
                });

            modelBuilder.Entity("MentalCheck.API.Models.Insight", b =>
                {
                    b.Navigation("InsightDicas");
                });

            modelBuilder.Entity("MentalCheck.API.Models.Usuario", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("Insights");
                });
#pragma warning restore 612, 618
        }
    }
}
